#ALL THESE SETTINGS CAN ALSO BE ACCESSED
#THROUGH THE IN-GAME SETTING TAB INSIDE
#THE STARCATCHER'S GUIDE
#Range: 0 ~ 6
minigame_gui_scale = 3
#Range: -20.0 ~ 20.0
hit_delay = 0.0
#Allowed Values: METRIC, IMPERIAL, CHEESEBURGER, FOOTBALL, DEVELOPER_HEIGHT, BANANA, DUCK, SPACE_WHALE, SCIENTIFIC
units = "IMPERIAL"
#Allowed Values: ALPHABETICAL_UP, ALPHABETICAL_DOWN, MOD_UP, MOD_DOWN, RARITY_UP, RARITY_DOWN, CAUGHT_UP, CAUGHT_DOWN, FLUID_UP, FLUID_DOWN, SEASON_UP, SEASON_DOWN
sort = "ALPHABETICAL_DOWN"

