name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "087fc8672615c066ab64bb07e6796b3582ca506705a2042b20b3b1e5e3ef42bc"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
